In [1]:
import pandas as pd

In [2]:
language = pd.read_csv(r"C:\Users\eymem\Documents\GitHub\Population-Diversity-Study\countrylanguage.csv")

In [3]:
language.head()

  CountryCode    Language IsOfficial  Percentage
0         ABW       Dutch          T         5.3
1         ABW     English          F         9.5
2         ABW  Papiamento          F        76.7
3         ABW     Spanish          F         7.4
4         AFG     Balochi          F         0.9

In [4]:
language.shape

(984, 4)

In [5]:
language.dtypes

CountryCode     object
Language        object
IsOfficial      object
Percentage     float64
dtype: object

In [6]:
language.isna().sum()

CountryCode    0
Language       0
IsOfficial     0
Percentage     0
dtype: int64

In [7]:
language.drop(columns=['IsOfficial'], inplace=True)

In [8]:
language.isna().sum()

CountryCode    0
Language       0
Percentage     0
dtype: int64

In [9]:
language.duplicated().sum()

np.int64(0)

In [68]:
country["Country"].value_counts().sort_values(ascending=False)

Country
Aruba           1
Afghanistan     1
Angola          1
Anguilla        1
Albania         1
               ..
Yemen           1
Yugoslavia      1
South Africa    1
Zambia          1
Zimbabwe        1
Name: count, Length: 239, dtype: int64

In [69]:
country["Continent"].value_counts().sort_values(ascending=False)

Continent
Africa           58
Asia             51
Europe           46
North America    37
Oceania          28
South America    14
Antarctica        5
Name: count, dtype: int64

In [70]:
country["Region"].value_counts().sort_values(ascending=False)

Region
Caribbean                    24
Eastern Africa               20
Middle East                  18
Western Africa               17
Southern Europe              15
Southern and Central Asia    14
South America                14
Southeast Asia               11
Polynesia                    10
Eastern Europe               10
Western Europe                9
Central Africa                9
Central America               8
Eastern Asia                  8
Micronesia                    7
Northern Africa               7
Nordic Countries              7
Australia and New Zealand     5
Antarctica                    5
Southern Africa               5
North America                 5
Melanesia                     5
Baltic Countries              3
British Islands               2
Micronesia/Caribbean          1
Name: count, dtype: int64

In [10]:
country = pd.read_csv(r"C:\Users\eymem\Documents\GitHub\Population-Diversity-Study\country_sql.csv")

In [12]:
country_language = language.merge(country, on='CountryCode', how='left')

In [13]:
country_language.head()

,CountryCode,Language,Percentage,Country,Continent,Region,SurfaceArea,Population,LifeExpectancy
0,ABW,Dutch,5.3,Aruba,North America,Caribbean,193.0,103000.0,78.0
1,ABW,English,9.5,Aruba,North America,Caribbean,193.0,103000.0,78.0
2,ABW,Papiamento,76.7,Aruba,North America,Caribbean,193.0,103000.0,78.0
3,ABW,Spanish,7.4,Aruba,North America,Caribbean,193.0,103000.0,78.0
4,AFG,Balochi,0.9,Afghanistan,Asia,Southern and Central Asia,652090.0,22720000.0,45.0

In [14]:
country_language.tail()

,CountryCode,Language,Percentage,Country,Continent,Region,SurfaceArea,Population,LifeExpectancy
979,ZMB,Tongan,11.0,Zambia,Africa,Eastern Africa,752618.0,9169000.0,37.0
980,ZWE,English,2.2,Zimbabwe,Africa,Eastern Africa,390757.0,11669000.0,37.0
981,ZWE,Ndebele,16.2,Zimbabwe,Africa,Eastern Africa,390757.0,11669000.0,37.0
982,ZWE,Nyanja,2.2,Zimbabwe,Africa,Eastern Africa,390757.0,11669000.0,37.0
983,ZWE,Shona,72.1,Zimbabwe,Africa,Eastern Africa,390757.0,11669000.0,37.0

In [15]:
country_language.drop(columns=['LifeExpectancy', "Population", "SurfaceArea", "Region", "Continent"], inplace=True)

In [18]:
country_language["Percentage"].describe()

count    984.000000
mean      20.374390
std       30.829452
min        0.000000
25%        1.275000
50%        5.300000
75%       21.125000
max      100.000000
Name: Percentage, dtype: float64

In [20]:
country_language.head()

  CountryCode    Language  Percentage      Country
0         ABW       Dutch         5.3        Aruba
1         ABW     English         9.5        Aruba
2         ABW  Papiamento        76.7        Aruba
3         ABW     Spanish         7.4        Aruba
4         AFG     Balochi         0.9  Afghanistan

In [21]:
language_sql = language.to_csv(r"C:\Users\eymem\Documents\GitHub\Population-Diversity-Study\language_sql.csv",index=False)