In [1]:
import pandas as pd

In [21]:
country = pd.read_csv(r"C:\Users\eymem\Documents\GitHub\Population-Diversity-Study\country.csv")

In [22]:
country.head()

,Code,Name,Continent,Region,SurfaceArea,IndepYear,Population,LifeExpectancy,GNP,GNPOld,LocalName,GovernmentForm,HeadOfState,Capital,Code2
0,ABW,Aruba,North America,Caribbean,193.0,NaN,103000,78.4,828.0,793.0,Aruba,Nonmetropolitan Territory of The Netherlands,Beatrix,129.0,AW
1,AFG,Afghanistan,Asia,Southern and Central Asia,652090.0,1919.0,22720000,45.9,5976.0,NaN,Afganistan/Afqanestan,Islamic Emirate,Mohammad Omar,1.0,AF
2,AGO,Angola,Africa,Central Africa,1246700.0,1975.0,12878000,38.3,6648.0,7984.0,Angola,Republic,José Eduardo dos Santos,56.0,AO
3,AIA,Anguilla,North America,Caribbean,96.0,NaN,8000,76.1,63.2,NaN,Anguilla,Dependent Territory of the UK,Elisabeth II,62.0,AI
4,ALB,Albania,Europe,Southern Europe,28748.0,1912.0,3401200,71.6,3205.0,2500.0,Shqipëria,Republic,Rexhep Mejdani,34.0,AL

In [23]:
country.shape

(239, 15)

In [24]:
country.dtypes

Code               object
Name               object
Continent          object
Region             object
SurfaceArea       float64
IndepYear         float64
Population          int64
LifeExpectancy    float64
GNP               float64
GNPOld            float64
LocalName          object
GovernmentForm     object
HeadOfState        object
Capital           float64
Code2              object
dtype: object

In [25]:
country.isna().sum()

Code               0
Name               0
Continent          0
Region             0
SurfaceArea        0
IndepYear         47
Population         0
LifeExpectancy    17
GNP                0
GNPOld            61
LocalName          0
GovernmentForm     0
HeadOfState        3
Capital            7
Code2              1
dtype: int64

In [26]:
country.drop(columns=['GNPOld', 'IndepYear', 'HeadOfState', 'GovernmentForm', 'LocalName', 'Code2', 'GNP', "Capital"], inplace=True)

In [27]:
country.isna().sum()

Code               0
Name               0
Continent          0
Region             0
SurfaceArea        0
Population         0
LifeExpectancy    17
dtype: int64

In [28]:
country.dropna(subset=['LifeExpectancy'], inplace=True)

In [29]:
country.isna().sum()

Code              0
Name              0
Continent         0
Region            0
SurfaceArea       0
Population        0
LifeExpectancy    0
dtype: int64

In [30]:
country.duplicated().sum()

np.int64(0)

In [31]:
country.rename(columns={"Name": "Country", "Code": "CountryCode"}, errors="ignore", inplace=True)

In [32]:
country.head()

,CountryCode,Country,Continent,Region,SurfaceArea,Population,LifeExpectancy
0,ABW,Aruba,North America,Caribbean,193.0,103000,78.4
1,AFG,Afghanistan,Asia,Southern and Central Asia,652090.0,22720000,45.9
2,AGO,Angola,Africa,Central Africa,1246700.0,12878000,38.3
3,AIA,Anguilla,North America,Caribbean,96.0,8000,76.1
4,ALB,Albania,Europe,Southern Europe,28748.0,3401200,71.6

In [33]:
country["Country"].value_counts().sort_values(ascending=False)

Country
Aruba           1
Afghanistan     1
Angola          1
Anguilla        1
Albania         1
               ..
Yemen           1
Yugoslavia      1
South Africa    1
Zambia          1
Zimbabwe        1
Name: count, Length: 222, dtype: int64

In [34]:
country["Continent"].value_counts().sort_values(ascending=False)

Continent
Africa           57
Asia             51
Europe           44
North America    37
Oceania          20
South America    13
Name: count, dtype: int64

In [35]:
country["Region"].value_counts().sort_values(ascending=False)

Region
Caribbean                    24
Eastern Africa               19
Middle East                  18
Western Africa               17
Southern and Central Asia    14
Southern Europe              14
South America                13
Southeast Asia               11
Eastern Europe               10
Western Europe                9
Central Africa                9
Eastern Asia                  8
Central America               8
Micronesia                    7
Northern Africa               7
Polynesia                     6
Nordic Countries              6
Southern Africa               5
North America                 5
Melanesia                     5
Baltic Countries              3
Australia and New Zealand     2
British Islands               2
Name: count, dtype: int64

In [36]:
country[["SurfaceArea", "Population","LifeExpectancy"]].describe()

        SurfaceArea    Population  LifeExpectancy
count  2.220000e+02  2.220000e+02      222.000000
mean   6.114811e+05  2.738162e+07       66.486036
std    1.803517e+06  1.132310e+08       11.519267
min    1.500000e+00  6.000000e+03       37.200000
25%    6.911500e+03  4.462500e+05       60.300000
50%    9.099100e+04  4.753000e+06       70.150000
75%    4.471875e+05  1.607925e+07       75.500000
max    1.707540e+07  1.277558e+09       83.500000

In [37]:
country.head()

,CountryCode,Country,Continent,Region,SurfaceArea,Population,LifeExpectancy
0,ABW,Aruba,North America,Caribbean,193.0,103000,78.4
1,AFG,Afghanistan,Asia,Southern and Central Asia,652090.0,22720000,45.9
2,AGO,Angola,Africa,Central Africa,1246700.0,12878000,38.3
3,AIA,Anguilla,North America,Caribbean,96.0,8000,76.1
4,ALB,Albania,Europe,Southern Europe,28748.0,3401200,71.6

In [38]:
country_sql = country.to_csv(r"C:\Users\eymem\Documents\GitHub\Population-Diversity-Study\country_sql.csv",index=False)