In [1]:
import pandas as pd

In [2]:
language = pd.read_csv(r"C:\Users\eymem\Documents\GitHub\Population-Diversity-Study\countrylanguage.csv")

In [3]:
language.head()

  CountryCode    Language IsOfficial  Percentage
0         ABW       Dutch          T         5.3
1         ABW     English          F         9.5
2         ABW  Papiamento          F        76.7
3         ABW     Spanish          F         7.4
4         AFG     Balochi          F         0.9

In [4]:
language.shape

(984, 4)

In [5]:
language.dtypes

CountryCode     object
Language        object
IsOfficial      object
Percentage     float64
dtype: object

In [6]:
language.isna().sum()

CountryCode    0
Language       0
IsOfficial     0
Percentage     0
dtype: int64

In [7]:
language.drop(columns=['IsOfficial'], inplace=True)

In [8]:
language.isna().sum()

CountryCode    0
Language       0
Percentage     0
dtype: int64

In [9]:
language.duplicated().sum()

np.int64(0)

In [12]:
language["Percentage"].describe()

count    984.000000
mean      20.374390
std       30.829452
min        0.000000
25%        1.275000
50%        5.300000
75%       21.125000
max      100.000000
Name: Percentage, dtype: float64

In [13]:
language["Language"].value_counts().sort_values()

Language
Gisu               1
Kiga               1
Lango              1
Soqutri            1
Chaga and Pare     1
                  ..
German            19
French            25
Spanish           28
Arabic            33
English           60
Name: count, Length: 457, dtype: int64

In [10]:
language.head()

  CountryCode    Language  Percentage
0         ABW       Dutch         5.3
1         ABW     English         9.5
2         ABW  Papiamento        76.7
3         ABW     Spanish         7.4
4         AFG     Balochi         0.9

In [14]:
language_sql = language.to_csv(r"C:\Users\eymem\Documents\GitHub\Population-Diversity-Study\language_sql.csv",index=False)